stages:
  - build


.retry_once: &retry_on_script_failure
  retry:
    max: 1
    when: script_failure

.docker_job: &docker_job
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  after_script:
    - docker logout $CI_REGISTRY

build_image:
  <<: *retry_on_script_failure
  <<: *docker_job
  stage: build
  only:
    - tags
  script:
    - cd api
    - docker pull ${CI_REGISTRY_IMAGE}:latest || true
    - >-
      docker build
      --cache-from ${CI_REGISTRY_IMAGE}:latest
      -t ${CI_REGISTRY_IMAGE}:latest
      -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
      .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    - docker push ${CI_REGISTRY_IMAGE}:latest
